export const ErrorCode = {
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  CONFLICT: 'CONFLICT',
  UNAUTHORIZED_ACCESS:'UNAUTHORIZED_ACCESS',
  ERROR: 'ERROR',
};

